### ISSUE TITLE
how do i edit the local storage in coolmathgames?

### ISSUE THREAD

**Issue by aChenForLife** [Cracko298/Planet-Life-Cheat#1]
Hey, I was unable to find the local storage in Google Chrome. Could you provide more information?

**Comment by Cracko298** [comment]
Sure thing, after opening the Dev Console with CTRL+SHIFT+I, go over to:

Application > Local Storage 

Local Storage is a drop-down down menu of Application, which you can also access by Clicking on Aplication then on Local Storage

**Comment by aChenForLife** [comment]
Oh. Then I can't do it on my school computer because they blocked the
inspect element menu.

**Comment by Cracko298** [comment]
If you have a Dell computer or Windows machine, you can attempt to enter and edit it via Powershell or CMD prompt.

Sometimes, schools and organizations forget that powershell exists and only block CMD Prompt.

I can't really help with commands as I don't know your laptop directory layout, but you might want to try and lookup CMD commands.

Such as cd "Directory", and dir

**Comment by Cracko298** [comment]
closed the issue, seems to be resolved. User is unable to access Local Storage from dev-console.

Reopen if needed or issue needs more addressing.

**Comment by Cracko298** [comment]
closed the issue, seems to be resolved. User is unable to access Local Storage from dev-console.

Reopen if needed or issue needs more addressing.
